//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModelDBFirst
{
    using System;
    using System.Collections.Generic;
    
    public partial class Book
    {
        public int Id { get; set; }
        public string title { get; set; }
        public int Authors_id { get; set; }
        public int Publisher_id { get; set; }
    
        public virtual Authors Authors { get; set; }
        public virtual Publisher Publisher { get; set; }
    }
}
